/* Basanos — serif display font.
 *
 * The second half of the type pairing. The 5x7 sans in font5x7.c carries dense
 * list rows where every pixel of width matters; this proportional serif carries
 * titles, the wordmark and figures — the places where the instrument should
 * look like an instrument rather than a hobby project.
 *
 * Proportional, so an "i" does not occupy the same cell as a "W". Generated by
 * tools/mkfont.py; see font_serif.c for the source face and licence.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef BASANOS_FONT_SERIF_H
#define BASANOS_FONT_SERIF_H

#include <stdint.h>

#define BAS_SERIF_H     17     /* rows per glyph                            */
#define BAS_SERIF_FIRST 32     /* first codepoint in the table              */
#define BAS_SERIF_COUNT 95     /* through 126                               */

typedef struct {
    uint8_t  w;                       /* ink width                          */
    uint8_t  adv;                     /* advance to the next glyph          */
    uint32_t rows[BAS_SERIF_H];       /* bit x = pixel at x, left to right   */
} bas_glyph_t;

extern const bas_glyph_t bas_serif[BAS_SERIF_COUNT];

#endif /* BASANOS_FONT_SERIF_H */
