#!/usr/bin/env python3
"""Generate the serif display font from a TTF.

The device carries two faces, which is the whole point of the pairing: a
compact 5x7 sans for dense list rows where every pixel of width is needed, and
this proportional serif for titles, the wordmark and figures — the places where
the instrument should look like an instrument.

Serifs disappear below about twelve pixels, so this is rendered at a display
size and never used for body text.

    tools/mkfont.py FONT.ttf --size 17 --out main/font_serif.c [--preview]

Committed so the font can be regenerated rather than hand-maintained.
"""
import argparse
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("needs Pillow: pip install pillow")

FIRST, LAST = 32, 126
MAX_W = 20


def render(path, size, weight=None):
    font = ImageFont.truetype(path, size)

    # A variable font defaults to Regular. At this size a Regular serif goes
    # thin and grey once thresholded, so the display face is pulled to Bold --
    # which is also what makes the wordmark read the way it does in the brand.
    if weight is not None:
        try:
            font.set_variation_by_axes([weight])
        except Exception:
            try:
                font.set_variation_by_name("Bold")
            except Exception:
                pass

    # One pass to find the common baseline, so every glyph sits on the same
    # line rather than each being cropped to its own ink.
    top, bot = 99, -99
    for cp in range(FIRST, LAST + 1):
        box = font.getbbox(chr(cp))
        if box and box[3] > box[1]:
            top = min(top, box[1])
            bot = max(bot, box[3])
    height = bot - top

    glyphs = []
    for cp in range(FIRST, LAST + 1):
        ch = chr(cp)
        adv = int(round(font.getlength(ch)))
        box = font.getbbox(ch)
        w = min(max(box[2], adv, 1), MAX_W) if box else max(adv, 1)

        img = Image.new("L", (MAX_W, height), 0)
        ImageDraw.Draw(img).text((0, -top), ch, font=font, fill=255)

        rows = []
        for y in range(height):
            bits = 0
            for x in range(MAX_W):
                # A hard threshold rather than antialiasing: the panel has no
                # intermediate shade to spend, and a mid-grey pixel on white
                # reads as dirt rather than as a smoother edge.
                if img.getpixel((x, y)) >= 128:
                    bits |= (1 << x)
            rows.append(bits)

        glyphs.append({"cp": cp, "adv": max(adv, 1), "w": w, "rows": rows})
    return height, glyphs


def preview(height, glyphs, text):
    for ln in range(height):
        out = ""
        for c in text:
            g = glyphs[ord(c) - FIRST]
            row = g["rows"][ln]
            out += "".join("#" if (row >> x) & 1 else "." for x in range(g["adv"]))
        print(out)


def emit(height, glyphs, src, size, out, weight):
    w = open(out, "w")
    w.write(f"""/* Basanos — serif display font, {height} px.
 *
 * GENERATED by tools/mkfont.py from {src} at {size} px, weight {weight}.
 * Do not hand-edit; regenerate instead.
 *
 * Source face: Noto Serif, SIL Open Font License 1.1. Chosen for its sturdy
 * transitional serifs, which survive a hard threshold at this size where a
 * Garamond's fine strokes would dissolve. The OFL permits redistribution
 * including embedding; see NOTICE.
 *
 * Bit x of each row is the pixel at that x, so a row reads left to right from
 * the least significant bit.
 *
 * SPDX-License-Identifier: MIT
 */
#include "font_serif.h"

const bas_glyph_t bas_serif[BAS_SERIF_COUNT] = {{
""")
    for g in glyphs:
        ch = chr(g["cp"])
        label = {"\\": "backslash", "'": "quote", '"': "dquote"}.get(ch, ch)
        rows = ", ".join(f"0x{r:05X}" for r in g["rows"])
        w.write(f"    {{ {g['w']:2d}, {g['adv']:2d}, {{ {rows} }} }},"
                f"  /* {label} */\n")
    w.write("};\n")
    w.close()
    print(f"wrote {out}: {len(glyphs)} glyphs, {height} px, "
          f"{len(glyphs) * (2 + height * 4)} bytes of table")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("--size", type=int, default=17)
    ap.add_argument("--weight", type=int, default=700,
                    help="variable-font weight axis; 0 for static")
    ap.add_argument("--out", default="main/font_serif.c")
    ap.add_argument("--preview", action="store_true")
    a = ap.parse_args()

    height, glyphs = render(a.ttf, a.size, a.weight or None)
    if a.preview:
        print(f"height {height}px")
        preview(height, glyphs, "BASANOS")
        print()
        preview(height, glyphs, "Channels 436")
        return
    emit(height, glyphs, a.ttf, a.size, a.out, a.weight)


if __name__ == "__main__":
    main()
